typography_spectrum: 0.9429791201837361
color:
  brandStrength: 0.9842952452600002
  lightness: 0.8899723847862333
  saturation: 0.40954659483395517
  rhythmicContrast: 0.3573968424461782
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.3368303014431149
author:
  name: Rogier van der Heide
  email: rogier@rogiervanderheide.com
  url: www.rogiervanderheide.com
name: Rogier van der Heide
navigation:
  - name: >-
      Where to Eat Pizza: Phaidon presents the ultimate pizza bucket list |
      Lifestyle | Wallpaper* Magazine
    id: 9e1ac5e4-57ea-4c3e-a0d2-66ec26f5cb28
    type: content
title: Rogier van der Heide
description: The world's best lighting designer from Liechtenstein
